version: '3.8'
services: 
  users-service-db:
    image: mysql:5.7.20
    container_name: users-service-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports: 
      - 7201:3306

  chat-service-db:
    image: mysql:5.7.20
    container_name: chat-service-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports: 
      - 7200:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 7300:80
    volumes: 
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - chat-service-db
      - users-service-db

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    
  chat-app:
    container_name: chat-app

  chat-service:
    container_name: chat-service

  users-service:
    container_name: users-service